server:
    port: 8888
    error:
        include-message: always
        include-binding-errors: always

spring:
    profiles.active: native
    application.name: config-server
    cloud.config:
        server.native.searchLocations: file:@parent.basedir@/../config/repo
        fail-fast: true
        retry:
            initial-interval: 3000
            multiplier: 1.3
            max-interval: 10000
            max-attempts: 20
        uri: http://${CONFIG_SERVER_USR}:${CONFIG_SERVER_PWD}@${app.config-server.host}:${app.config-server.port}
    security.user:
        name: dev-usr
        password: dev-pwd
# WARNING: Exposing all management endpoints over http should only
#          be used during development, must be locked down in production!
management:
    endpoint.health.show-details: "ALWAYS"
    endpoints.web.exposure.include: "*"

logging.level.root: info
app.config-server:
    host: localhost
    port: 8888

CONFIG_SERVER_USR: dev-usr

CONFIG_SERVER_PWD: dev-pwd
---
spring:
    config.activate.on-profile: docker
    cloud.config.server.native.searchLocations: file:/config/repo